- name: Install Docker
  hosts: swot
  remote_user: joseph
  become: yes

  tasks:
    # Taken from https://yasha.solutions/install-docker-on-debian-with-ansible/
    - name: Update the apt package index
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install packages for apt add repository over HTTPS
      become: yes
      apt:
        name: "{{ packagesdep }}"
        force_apt_get: yes
        state: latest
        update_cache: yes
      vars:
        packagesdep:
        - git
        - apt-transport-https
        - ca-certificates
        - wget
        - software-properties-common
        - gnupg2
        - curl

    - name: Add Apt signing key from official docker repo
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: add docker official repository for Debian Stretch
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        state: present

    - name: Index new repo into the cache
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install Docker
      apt:
        name: "docker-ce"
        state: latest

    - name: Send Discord notification
      discord_webhook:
        webhook_url: "{{ discord_webhook }}"
        content: ":whale2: docker installed"

    - name: Install Pip
      apt:
        name: python3-pip
        state: latest

    - name: Install Docker Python client
      pip:
        name: docker
