- name: Deploy Swot web
  hosts: swot
  remote_user: joseph
  become: yes

  tasks:
    - name: Send Discord notification
      discord_webhook:
        webhook_url: "{{ discord_webhook }}"
        content: ":new: deploying swot"

    - name: Setup config file
      template:
        src: files/swot_config.yaml
        dest: /opt/swot/config.yaml
        mode: '0644'

    - name: Pull Swot latest from GitHub
      docker_image:
        name: docker.pkg.github.com/j03b/swot-backend/swot:main
        source: pull
        force_source: true

    - name: Send Discord notification
      discord_webhook:
        webhook_url: "{{ discord_webhook }}"
        content: ":arrow_down: pulled latest swot from github"

    - name: Start Swot container
      docker_container:
        name: swotweb
        image: docker.pkg.github.com/j03b/swot-backend/swot:main
        networks_cli_compatible: no
        networks:
          - name: "{{ network_name }}"
        volumes:
          - /opt/swot/config.yaml:/app/config.yaml
        restart: true
        env:
          DATABASE_URL: "{{ database_url }}"

    - name: Send Discord notification
      discord_webhook:
        webhook_url: "{{ discord_webhook }}"
        content: ":whale2: swotweb has been restarted"

    - name: Prune Docker images
      docker_prune:
        images: yes
        images_filters:
          dangling: false

    - name: Send Discord notification
      discord_webhook:
        webhook_url: "{{ discord_webhook }}"
        content: ":put_litter_in_its_place: docker images pruned"
