host:
  host: "0.0.0.0"
  port: 80
  debug: false
  migrate_on_startup: true

recaptcha:
  key: "{{ recaptcha_key }}"

flask:
  SECRET_KEY: "{{ flask_secret_key }}"

db:
  use_sqlite: false

  host: "postgres"
  port: 5432

  username: "{{ postgres_user}}"
  password: "{{ postgres_password}}"
  database: "{{ postgres_user }}"
